algorithm:
  batch_size: 512
  dataset:
    max_capacity: 100000000
    num_data_workers: 4
    train_dataset_path: ../../data/datasets/PendulumWithContact/rss-new/trajectory_len-100_10M_train.hdf5
    valid_datasets:
      exp_trajectory: ../../data/datasets/PendulumWithContact/rss-new/trajectory_len-100_valid.hdf5
      fixed_ground_passive: ../../data/datasets/PendulumWithContact/rss/trajectory_len-100_fixed-ground_passive_valid.hdf5
  eval:
    dataset_path: ../../data/datasets/PendulumWithContact/rss/trajectory_len-100_fixed-ground_passive_valid.hdf5
    mode: dataset
    num_rollouts: 2048
    passive: true
    rollout_horizon: 10
  grad_norm: 1.0
  name: SequenceModelTrainer
  num_epochs: 1000
  num_iters_per_epoch: 5000
  num_valid_batches: 100
  optimizer:
    lr_end: 1e-4
    lr_schedule: linear
    lr_start: 1e-3
  sample_sequence_length: 10
  seed: 0
  truncate_grad: true
cli:
  cfg: ./cfg/Pendulum/rss/transformer.yaml
  cfg_overrides: ' algorithm.dataset.train_dataset_path ../../data/datasets/PendulumWithContact/rss-new/trajectory_len-100_10M_train.hdf5
    algorithm.dataset.valid_datasets.exp_trajectory ../../data/datasets/PendulumWithContact/rss-new/trajectory_len-100_valid.hdf5
    env.neural_integrator_cfg.states_frame body network.transformer.n_layer 6 network.transformer.n_embd
    192 algorithm.sample_sequence_length 10 env.neural_integrator_cfg.num_states_history
    10'
  checkpoint: null
  device: cuda:5
  eval_interval: 1
  log_interval: 1
  logdir: ../../data/trained_models/Pendulum/rss-new-1-22/transformer/ngc_dataset-act_states_frame-body_n_layer-6_n_embd-192_seq_length-10/run-0
  no_time_stamp: true
  render: false
  save_interval: 50
  test: false
  train: true
env:
  env_name: PendulumWithContact
  neural_integrator_cfg:
    anchor_frame_step: every
    name: TransformerNeuralIntegrator
    num_states_history: 10
    prediction_type: relative
    states_embedding_type: identical
    states_frame: body
  num_envs: 512
  render: false
inputs:
  low_dim:
  - states_embedding
  - contact_normals
  - contact_points_1
  - contact_depths
  - joint_acts
  - gravity_dir
network:
  encoder:
    low_dim:
      activation: relu
      layer_sizes: []
      layernorm: false
  model:
    mlp:
      activation: relu
      layer_sizes:
      - 64
      layernorm: false
    output_tanh: false
  normalize_input: true
  normalize_output: true
  transformer:
    bias: false
    block_size: 16
    dropout: 0.0
    n_embd: 192
    n_head: 12
    n_layer: 6
