env:
  env_mode: neural
  env_name: AnymalJointPositionControl
  max_episode_length: 1000
  model_path: ../../pretrained_models/NeRD_models/Anymal/model/nn/model.pt
  num_envs: 2048
  reward_bias: 0.0
  warp_env_cfg:
    camera_tracking: true
    obs_type: dflex
    random_reset: true
    seed: 20
    setup_renderer: false
    task: forward
rl:
  config:
    bounds_loss_coef: 0.0001
    clip_value: true
    critic_coef: 4
    e_clip: 0.2
    entropy_coef: 0.0
    full_experiment_name: AnymalPPO/4-29/forward_walk_1/joint_position_control/nerd_jpc-random-pd_10M_T-10//04-29-2025-03-34-35
    gamma: 0.99
    grad_norm: 1.0
    horizon_length: 32
    kl_threshold: 0.008
    learning_rate: 0.0003
    lr_schedule: adaptive
    max_epochs: 1000
    mini_epochs: 5
    minibatch_size: 16384
    name: AnymalPPO
    normalize_advantage: true
    normalize_input: true
    normalize_value: true
    player:
      determenistic: true
      games_num: 2
      num_actors: 3
      print_stats: true
    reward_shaper:
      scale_value: 1.0
    save_best_after: 10
    save_frequency: 50
    score_to_win: 3000000
    seq_length: 8
    tau: 0.95
    truncate_grads: true
  network:
    mlp:
      activation: relu
      d2rl: false
      initializer:
        name: default
      regularizer:
        name: None
      units:
      - 128
      - 64
      - 32
  other_params:
    fixed_sigma: true
seed: 20
