env:
  env_mode: neural
  env_name: Ant
  max_episode_length: 500
  model_path: ../../pretrained_models/NeRD_models/Ant/model/nn/model.pt
  num_envs: 2048
  reward_bias: 0.0
  warp_env_cfg:
    camera_tracking: true
    obs_type: dflex
    random_reset: true
    seed: 1
    setup_renderer: false
    task: run
rl:
  config:
    bounds_loss_coef: 0.0001
    clip_value: true
    critic_coef: 4
    e_clip: 0.2
    entropy_coef: 0.0
    full_experiment_name: AntPPO/batch_experiments_final_final/500-epoch/run/neural/01-26-2025-18-07-37
    gamma: 0.99
    grad_norm: 1.0
    horizon_length: 32
    kl_threshold: 0.008
    learning_rate: 0.0003
    lr_schedule: adaptive
    max_epochs: 500
    mini_epochs: 5
    minibatch_size: 16384
    name: AntPPO
    normalize_advantage: true
    normalize_input: true
    normalize_value: true
    player:
      determenistic: true
      games_num: 2
      num_actors: 3
      print_stats: true
    reward_shaper:
      scale_value: 1.0
    save_best_after: 10
    save_frequency: 50
    score_to_win: 3000000
    seq_length: 8
    tau: 0.95
    truncate_grads: true
  network:
    mlp:
      activation: relu
      d2rl: false
      initializer:
        name: default
      regularizer:
        name: None
      units:
      - 128
      - 64
      - 32
seed: 1
