env:
  env_name: FrankaReach
  env_mode: neural
  model_path: ../../pretrained_models/NeRD_models/Franka/model/nn/model.pt
  num_envs: 1024

  max_episode_length: 128
  reward_bias: 0.
  control_steps: 1

  warp_env_cfg:
    random_reset: True
    random_target: True
    control_mode: joint_torque_control

rl:
  config:
    name: FrankaPPO
    max_epochs: 200
    horizon_length: 128
    normalize_input: True
    normalize_value: True
    reward_shaper:
      scale_value: 1.
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 0.0003
    lr_schedule: adaptive
    kl_threshold: 0.008
    score_to_win: 30000
    save_best_after: 10
    save_frequency: 50
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    minibatch_size: 8192
    mini_epochs: 8
    # minibatch_size: 16384
    # mini_epochs: 5
    critic_coef: 4
    clip_value: True
    seq_length: 8
    bounds_loss_coef: 0.0001
    
    player:
      determenistic: True
      games_num: 2
      num_actors: 3
      print_stats: True
  
  network:
    mlp:
      units: [64, 64]
      activation: relu
      d2rl: False
      initializer:
        name: default
      regularizer:
        name: None
    rnn:
      name: lstm
      before_mlp: True
      concat_input: true
      layer_norm: true
      layers: 2
      units: 256
    
  other_params:
    fixed_sigma: False
  



