env:
  control_steps: 2
  env_mode: neural
  env_name: FrankaReach
  max_episode_length: 128
  model_path: ../../pretrained_models/NeRD_models/Franka/model/nn/model.pt
  num_envs: 1024
  reward_bias: 0.0
  warp_env_cfg:
    control_mode: joint_position_control
    random_reset: true
    random_target: true
    seed: 20
    setup_renderer: false
rl:
  config:
    bounds_loss_coef: 0.0001
    clip_value: true
    critic_coef: 4
    e_clip: 0.2
    entropy_coef: 0.0
    full_experiment_name: test/joint_position_control//08-13-2025-17-52-11
    gamma: 0.99
    grad_norm: 1.0
    horizon_length: 128
    kl_threshold: 0.008
    learning_rate: 0.0003
    lr_schedule: adaptive
    max_epochs: 200
    mini_epochs: 8
    minibatch_size: 8192
    name: FrankaPPO
    normalize_advantage: true
    normalize_input: true
    normalize_value: true
    player:
      determenistic: true
      games_num: 2
      num_actors: 3
      print_stats: true
    reward_shaper:
      scale_value: 1.0
    save_best_after: 10
    save_frequency: 50
    score_to_win: 30000
    seq_length: 8
    tau: 0.95
    truncate_grads: true
  network:
    mlp:
      activation: relu
      d2rl: false
      initializer:
        name: default
      regularizer:
        name: None
      units:
      - 64
      - 64
    rnn:
      before_mlp: true
      concat_input: true
      layer_norm: true
      layers: 2
      name: lstm
      units: 256
  other_params:
    fixed_sigma: false
seed: 20
